auth:
  username: r2devops
  database: r2devops
  existingSecret: postgresql-secret
  secretKeys:
    adminPasswordKey: POSTGRES_PASSWORD
    userPasswordKey: APP_DB_PASSWORD

primary:
  persistence:
    storageClass: 'longhorn'

service:
  type: ClusterIP
  ports:
    postgresql: 5432

# Backup and monitoring options
backup:
  enabled: true
  cronjob:
    schedule: '0 2 * * *' # Daily backup at 2 AM
    storage:
      storageClass: 'longhorn'

tls:
  enabled: true
  certificatesSecret: "r2devops-postgresql-r2devops-svc-k8s-demo-01-local-tls"